CREATE TABLE public.Incoming_Documents
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_number   VARCHAR(255),
    document_date     TIMESTAMP WITHOUT TIME ZONE,
    sender            VARCHAR(255),
    recipient         VARCHAR(255),
    title             VARCHAR(255),
    description       VARCHAR(255),
    es_signature      BYTEA,
    processing_status VARCHAR(255),
    CONSTRAINT pk_incoming_documents PRIMARY KEY (id)
);
