CREATE TABLE public.Incoming_Documents_Processing_History
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incoming_document_id INTEGER                                  NOT NULL,
    status               VARCHAR(255),
    status_date          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_incoming_documents_processing_history PRIMARY KEY (id)
);