CREATE TABLE public.Interdepartmental_Requests
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mu_id              INTEGER                                  NOT NULL,
    request_type       VARCHAR(255),
    name               VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    responsible_person VARCHAR(255),
    status             VARCHAR(255),
    CONSTRAINT pk_interdepartmental_requests PRIMARY KEY (id)
);