CREATE TABLE public.Interdepartmental_Requests_Processing_History
(
    id                           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    interdepartmental_request_id INTEGER                                  NOT NULL,
    status                       VARCHAR(255),
    status_date                  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_interdepartmental_requests_processing_history PRIMARY KEY (id)
);