CREATE TABLE public.Interdepartmental_Request_Types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_interdepartmental_request_types PRIMARY KEY (id)
);