CREATE TABLE public.MUs
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incoming_doc_id INTEGER                                  NOT NULL,
    deadline        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_mus PRIMARY KEY (id)
);