CREATE TABLE public.Requested_Documents
(
    id                           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    interdepartmental_request_id INTEGER                                  NOT NULL,
    request                      VARCHAR(255),
    response                     VARCHAR(255),
    response_date                TIMESTAMP WITHOUT TIME ZONE,
    es_signature                 BYTEA,
    CONSTRAINT pk_requested_documents PRIMARY KEY (id)
);